package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateShimScript(t *testing.T) {
	script := generateShimScript("docker.exe")

	if !strings.Contains(script, "#!/bin/sh") {
		t.Error("shim script missing shebang")
	}
	if !strings.Contains(script, "Generated by winrun shim install") {
		t.Error("shim script missing marker comment")
	}
	if !strings.Contains(script, "docker.exe") {
		t.Error("shim script missing binary name")
	}
	if !strings.Contains(script, `"$@"`) {
		t.Error("shim script missing argument passthrough")
	}
	if !strings.Contains(script, "--convert-paths") {
		t.Error("shim script missing --convert-paths flag")
	}
}

func TestShimInstallAndRemove(t *testing.T) {
	// Use a temp directory as the bin dir.
	tmpDir := t.TempDir()

	// Simulate install.
	shimPath := filepath.Join(tmpDir, "docker")
	content := generateShimScript("docker.exe")
	if err := os.WriteFile(shimPath, []byte(content), 0o755); err != nil {
		t.Fatalf("failed to write shim: %v", err)
	}

	// Verify the file exists and is executable.
	info, err := os.Stat(shimPath)
	if err != nil {
		t.Fatalf("shim not found: %v", err)
	}
	if info.Mode()&0o111 == 0 {
		t.Error("shim is not executable")
	}

	// Verify content.
	data, _ := os.ReadFile(shimPath)
	if !strings.Contains(string(data), "docker.exe") {
		t.Error("shim content doesn't contain the binary name")
	}

	// Simulate remove (verify marker check).
	readContent, _ := os.ReadFile(shimPath)
	if !strings.Contains(string(readContent), "Generated by winrun shim install") {
		t.Error("marker not found in shim")
	}

	if err := os.Remove(shimPath); err != nil {
		t.Fatalf("failed to remove shim: %v", err)
	}

	if _, err := os.Stat(shimPath); !os.IsNotExist(err) {
		t.Error("shim still exists after removal")
	}
}

func TestShimAutoDeriveName(t *testing.T) {
	// Test that "docker.exe" → "docker" name derivation works.
	binary := "docker.exe"
	name := strings.TrimSuffix(filepath.Base(binary), ".exe")
	if name != "docker" {
		t.Errorf("auto-derived name = %q, want %q", name, "docker")
	}

	// With path.
	binary = "/mnt/c/Program Files/Docker/docker.exe"
	name = strings.TrimSuffix(filepath.Base(binary), ".exe")
	if name != "docker" {
		t.Errorf("auto-derived name = %q, want %q", name, "docker")
	}
}
